"use client";

import { useEffect } from "react";
import { createPortal } from "react-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface ReportViewerProps {
  /** Already-built Markdown string to render. */
  markdown: string;
  /** Banner subtitle line (candidate · product · date). */
  subtitle?: string;
  /** Called when the user dismisses the modal. */
  onClose: () => void;
  /**
   * Optional. When supplied, a "Print to PDF" button appears in the modal
   * footer. The viewer stays presentational; the host component owns the
   * print pipeline (same handler used by the standalone Print to PDF
   * button on the Progress page).
   */
  onPrint?: () => void;
}

/**
 * Full-screen report viewer modal.
 *
 * Renders the same Markdown that the .md / .html / .pdf exports use, with
 * Glacier Lab styling so the candidate (and any trainer looking over their
 * shoulder) can review the whole progress bundle without leaving the app.
 *
 * Escape key, the X button, and clicking on the dimmed backdrop all close
 * the modal. Body scroll is locked while it's open.
 */
export function ReportViewer({
  markdown,
  subtitle,
  onClose,
  onPrint,
}: ReportViewerProps) {
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = previousOverflow;
    };
  }, [onClose]);

  if (typeof document === "undefined") return null;

  const modal = (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Progress report"
      className="fixed inset-0 z-[100] flex items-stretch justify-center bg-ink/60 backdrop-blur-sm md:items-center md:p-6"
      onClick={onClose}
    >
      <div
        className="relative flex h-full w-full flex-col bg-paper-3 md:h-[88vh] md:max-w-4xl md:rounded-[4px] md:border md:border-rule md:shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header band */}
        <header className="flex shrink-0 items-center justify-between gap-3 border-b border-rule bg-paper-2 px-5 py-3 md:px-7 md:py-4">
          <div className="min-w-0">
            <p className="font-mono text-[9px] font-semibold uppercase tracking-[0.18em] text-ink-3">
              Progress report · Preview
            </p>
            {subtitle ? (
              <p className="mt-0.5 truncate font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-ink-2">
                {subtitle}
              </p>
            ) : null}
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close report"
            className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-[2px] border border-rule bg-paper-3 font-mono text-[14px] font-bold text-ink-2 hover:border-ink hover:text-ink"
          >
            ×
          </button>
        </header>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto bg-paper-3 px-5 py-6 md:px-12 md:py-10">
          <article className="report-prose mx-auto max-w-[68ch]">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                // Turn the bolded AI grade label into a coloured pill,
                // matching the styled HTML / PDF export. The label text is
                // generated by `buildProgressMarkdown` so the matching is
                // exact.
                strong({ children, ...rest }) {
                  const text =
                    Array.isArray(children)
                      ? children.join("")
                      : typeof children === "string"
                      ? children
                      : null;
                  const pill =
                    text === "AI grade — Met"
                      ? { cls: "grade-pill grade-met", label: "AI grade · Met" }
                      : text === "AI grade — Nearly"
                      ? { cls: "grade-pill grade-nearly", label: "AI grade · Nearly" }
                      : text === "AI grade — Not yet"
                      ? { cls: "grade-pill grade-not-yet", label: "AI grade · Not yet" }
                      : null;
                  if (pill) {
                    return <span className={pill.cls}>{pill.label}</span>;
                  }
                  return <strong {...rest}>{children}</strong>;
                },
              }}
            >
              {markdown}
            </ReactMarkdown>
          </article>
        </div>

        {/* Footer band */}
        <footer className="flex shrink-0 flex-wrap items-center justify-between gap-3 border-t border-rule bg-paper-2 px-5 py-3 md:px-7 md:py-4">
          <p className="font-mono text-[10px] uppercase tracking-[0.1em] text-ink-3">
            Esc or click outside to close
          </p>
          <div className="flex flex-wrap items-center gap-2">
            {onPrint ? (
              <button
                type="button"
                onClick={onPrint}
                className="btn red sm"
              >
                Print to PDF
              </button>
            ) : null}
            <button
              type="button"
              onClick={onClose}
              className="inline-flex items-center rounded-[2px] border border-rule bg-paper-3 px-3 py-1.5 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-ink-2 hover:border-ink hover:text-ink"
            >
              Close
            </button>
          </div>
        </footer>
      </div>

      <style jsx>{`
        .report-prose :global(h1) {
          font-size: 26px;
          font-weight: 800;
          letter-spacing: -0.02em;
          margin: 0 0 12px;
          color: var(--ink);
          border-bottom: 2px solid var(--ink);
          padding-bottom: 10px;
        }
        .report-prose :global(h2) {
          font-size: 18px;
          font-weight: 800;
          letter-spacing: -0.012em;
          margin: 28px 0 10px;
          color: var(--ink);
          border-bottom: 1px solid var(--rule);
          padding-bottom: 6px;
        }
        .report-prose :global(h3) {
          font-size: 15px;
          font-weight: 700;
          margin: 20px 0 8px;
          color: var(--ink);
        }
        .report-prose :global(h4) {
          font-size: 13.5px;
          font-weight: 700;
          margin: 16px 0 6px;
          color: var(--ink-2);
        }
        .report-prose :global(p) {
          margin: 0 0 10px;
          color: var(--ink-2);
          line-height: 1.55;
        }
        .report-prose :global(ul) {
          margin: 4px 0 12px;
          padding-left: 22px;
          color: var(--ink-2);
        }
        .report-prose :global(li) { margin: 2px 0; }
        .report-prose :global(blockquote) {
          margin: 6px 0 14px;
          padding: 10px 14px;
          background: var(--paper-2);
          border-left: 3px solid var(--ice, #2480b5);
          color: var(--ink);
          font-style: italic;
          white-space: pre-wrap;
        }
        .report-prose :global(hr) {
          border: none;
          border-top: 1px solid var(--rule);
          margin: 24px 0;
        }
        .report-prose :global(strong) { color: var(--ink); }
        .report-prose :global(em) { color: var(--ink-2); }
        .report-prose :global(.grade-pill) {
          display: inline-block;
          padding: 2px 9px;
          border-radius: 2px;
          font-weight: 700;
          color: #ffffff;
          letter-spacing: 0.01em;
        }
        .report-prose :global(.grade-pill.grade-met) {
          background: var(--moss, #6b8e23);
        }
        .report-prose :global(.grade-pill.grade-nearly) {
          background: #d49018;
        }
        .report-prose :global(.grade-pill.grade-not-yet) {
          background: var(--red, #d7263d);
        }
      `}</style>
    </div>
  );

  return createPortal(modal, document.body);
}
