// AUTO-GENERATED by scripts/build-flashcards-data.mjs.
// Edit FLASHCARDS_CONTENT.md and re-run `node scripts/build-flashcards-data.mjs`.

export interface Flashcard {
  id: string;
  title: string;
  front: string;
  back: string;
  tags: string[];
}

export interface Deck {
  id: string;
  title: string;
  description: string;
  primary: boolean;
  pseudo?: boolean;
  cardIds: string[];
}

export const FLASHCARDS: Flashcard[] = [
  {
    "id": "C7.1-01",
    "title": "Counting contour crossings",
    "front": "On a 10 m contour-interval map, how many contour lines do you cross going from 2,180 m to 2,260 m, and how much height have you gained?",
    "back": "**8 crossings, 80 m gained.** Crossings count transitions between bands, not the lines themselves.",
    "tags": [
      "L2",
      "C1.1",
      "contour-fundamentals"
    ]
  },
  {
    "id": "C7.1-02",
    "title": "Steepness from contour spacing",
    "front": "On a 1:25,000 map with 10 m contours, what spacing in millimetres corresponds to the 30° threshold?",
    "back": "Approximately **3 mm**. Closer than 3 mm → 30°+; well inside 3 mm (e.g. 2 mm) is steeper still.",
    "tags": [
      "L2",
      "C1.2",
      "steepness"
    ]
  },
  {
    "id": "C7.1-03",
    "title": "V-down contour pattern",
    "front": "Contours form a V pointing downhill. What feature is this?",
    "back": "A **spur** (or a ridge if the feature is long enough). The \"V points down on a spur\" is the inverse-pairing rule.",
    "tags": [
      "L2",
      "C2.3",
      "feature-recognition"
    ]
  },
  {
    "id": "C7.1-04",
    "title": "Bowl on the map",
    "front": "What contour pattern identifies a bowl?",
    "back": "A **U-shape or arc opening downhill**, with **tightly spaced contours at the back (the headwall)** and **wider spacing on the flanks**.",
    "tags": [
      "L2",
      "C3.1",
      "advanced-features"
    ]
  },
  {
    "id": "C7.1-05",
    "title": "Plateau on the map",
    "front": "What contour pattern identifies a plateau?",
    "back": "**A single closed loop around a broad nearly contour-free area**, often with a small spot height as the only altitude reference inside.",
    "tags": [
      "L2",
      "C3.2",
      "advanced-features"
    ]
  },
  {
    "id": "C7.1-06",
    "title": "Aspect to eight directions",
    "front": "A slope falls towards the lower-right corner of a north-up map. What is its aspect?",
    "back": "**South-east (SE).** If you answered S or E alone, the four-direction default has crept back in.",
    "tags": [
      "L2",
      "C4.2",
      "aspect"
    ]
  },
  {
    "id": "C7.1-07",
    "title": "Drawing the fall line",
    "front": "How do you draw the fall-line arrow at a point on a slope?",
    "back": "**Perpendicular to the contour at that point**, pointing **from the higher contour towards the lower contour**.",
    "tags": [
      "L2",
      "C4.1",
      "aspect"
    ]
  },
  {
    "id": "C7.1-08",
    "title": "Col vs summit",
    "front": "What's the contour-pattern difference between a summit and a col?",
    "back": "A **summit** = closed contour loops with the highest contour at the centre. A **col** = two opposite sides rising (towards two summits) and two opposite sides falling (towards two valleys).",
    "tags": [
      "L2",
      "C3.3",
      "advanced-features"
    ]
  },
  {
    "id": "C7.1-09",
    "title": "Bowl wind loading",
    "front": "Where in a bowl does wind-loaded snow accumulate?",
    "back": "In the **upper part of the bowl, just below the headwall**, on the lee side of the prevailing wind. Cornices may build on the rim above.",
    "tags": [
      "L2",
      "C3.1",
      "hazards"
    ]
  },
  {
    "id": "C7.1-10",
    "title": "Cliff band cues",
    "front": "Two cues together identify a cliff band on most national 1:25,000 alpine series. Name them.",
    "back": "**(1) Merged or near-merged contours** drawn as a single thick line. **(2) Rock symbology** overlaid (hatching on IGN, stippling on Swisstopo, rock-face shading on Alpenvereinskarte). Either alone can mislead; both together are diagnostic.",
    "tags": [
      "L2",
      "C3.4",
      "advanced-features"
    ]
  },
  {
    "id": "C7.1-11",
    "title": "Comfortable skinning gradient",
    "front": "What's the comfortable skinning gradient band, and the upper sustained limit?",
    "back": "**8–12° comfortable**, **up to 15° as the upper sustained limit**. The comfortable band is where the skin track works without effort; up to 15° is acceptable on a single traverse leg with kick turns.",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "C7.1-12",
    "title": "Skinning gradient in mm",
    "front": "On a 1:25,000 map with 10 m contours, what contour spacing corresponds to the upper end of the comfortable skinning band?",
    "back": "Approximately **5–6 mm**, using the C1.2 rule (≈3 mm = 30°, ≈5–6 mm = 12°).",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "C7.1-13",
    "title": "Terrain trap definition",
    "front": "Define a \"terrain trap\" in one sentence.",
    "back": "**A piece of ground where a small avalanche or fall produces disproportionate consequences** — because the configuration concentrates moving snow (gully), removes the exit (single-mouth bowl), or adds a vertical drop (cliff band below the slope). It's about the *consequence*, not just the slope angle.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "C7.1-14",
    "title": "Sketch task practice",
    "front": "Sketch the side profile of a sharp peak with two spurs running off it on different aspects. What four things should the sketch show?",
    "back": "(1) A **sharp peak** (narrow, pointed, steep flanks). (2) **Two spurs** as projections from the parent peak. (3) **Labels** for the summit and both spurs. (4) The two spurs facing in **different aspects** (a brief direction note for each).",
    "tags": [
      "L2",
      "C5.1",
      "visualisation"
    ]
  },
  {
    "id": "C7.1-15",
    "title": "Four-part standing description",
    "front": "Name the four parts of the C5.3 standing-description structure.",
    "back": "**(1) Underfoot. (2) Slope and aspect. (3) Near features. (4) Far features.**",
    "tags": [
      "L2",
      "C5.3",
      "visualisation"
    ]
  },
  {
    "id": "D10.1-01",
    "title": "Compass parts most confused",
    "front": "Which two parts of a baseplate compass are most commonly confused?",
    "back": "The **direction-of-travel arrow** (fixed on the baseplate, points where you're going) and the **orienting arrow** (on the floor of the rotating bezel, alignment target for the magnetic needle).",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "D10.1-02",
    "title": "Bearing reading standard",
    "front": "What's the IMS / EMS working standard for reading a bearing from a set compass?",
    "back": "**Within 2°, in under 60 seconds.** Both halves required.",
    "tags": [
      "L3",
      "D1.2",
      "compass"
    ]
  },
  {
    "id": "D10.1-03",
    "title": "Four-step bearing procedure",
    "front": "Name the four steps for taking a bearing from the map.",
    "back": "(1) **Place the baseplate edge along the line** from start to destination, DTA towards destination. (2) **Rotate the bezel** until the parallel orienting lines align with the grid lines. (3) **Take the compass off the map.** (4) **Read the bearing** from the DTA against the bezel scale.",
    "tags": [
      "L3",
      "D2.1",
      "bearings"
    ]
  },
  {
    "id": "D10.1-04",
    "title": "Magnetic variation rule",
    "front": "Grid bearing 178°, magnetic variation +2° east. What's the magnetic bearing?",
    "back": "**180°.** For east variation: **add** the variation to the grid bearing. (For west variation: subtract.)",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "D10.1-05",
    "title": "Walking-on-bearing drift target",
    "front": "What's the IMS / EMS working drift standard while walking on a bearing?",
    "back": "**Less than 15 m drift per 100 m of travel.**",
    "tags": [
      "L3",
      "D3.1",
      "ground-bearings"
    ]
  },
  {
    "id": "D10.1-06",
    "title": "Back bearing",
    "front": "Forward bearing 220° magnetic. What's the back bearing?",
    "back": "**40°.** For forward bearings ≥180°, **subtract 180°**. For forward bearings <180°, **add 180°**.",
    "tags": [
      "L3",
      "D3.2",
      "ground-bearings"
    ]
  },
  {
    "id": "D10.1-07",
    "title": "Resection setup",
    "front": "Resection requires what minimum number of features, and what angular separation produces the most accurate fix?",
    "back": "**Minimum 2 features**, optimal at **~90° separation**. Closer-together or near-opposite features give a shallow intersection where small bearing errors become large position errors.",
    "tags": [
      "L3",
      "D3.3",
      "ground-bearings"
    ]
  },
  {
    "id": "D10.1-08",
    "title": "Bearing-shapes drill closure",
    "front": "What's the IMS / EMS closure-error standard for a 100-pace square bearing-shapes drill?",
    "back": "**Less than 5 paces.**",
    "tags": [
      "L3",
      "D4.1",
      "accuracy"
    ]
  },
  {
    "id": "D10.1-09",
    "title": "Magnetic interference distances",
    "front": "Name the four common magnetic interference sources on a ski tour and the minimum safe distance for each.",
    "back": "- **Steel ski bindings: 50 cm**\n- **Ice axes: 50 cm**\n- **Mobile phones: 30 cm**\n- **Radio handsets: 30 cm**\n\nThe 50 cm vs 30 cm distinction is the **steel vs electronics** distinction.",
    "tags": [
      "L3",
      "D4.3",
      "accuracy"
    ]
  },
  {
    "id": "D10.1-10",
    "title": "Altimeter pressure rule",
    "front": "What's the rule of thumb converting altimeter drift to implied pressure change?",
    "back": "**1 hPa ≈ 8 m** of apparent altitude change (lower troposphere).",
    "tags": [
      "L3",
      "D5.1",
      "altimeter"
    ]
  },
  {
    "id": "D10.1-11",
    "title": "Five barometric trend bands",
    "front": "Name the five IMS Nav Programme barometric trend categories with their rate thresholds.",
    "back": "- **Rising** — any positive rate\n- **Steady** — <0.1 hPa/hr sustained for 3 hours\n- **Slow fall** — <0.5 hPa/hr (falling)\n- **Moderate fall** — 0.5 to 1.0 hPa/hr (falling)\n- **Rapid fall** — >1.0 hPa/hr (falling)",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "D10.1-12",
    "title": "Aspect-of-slope relocation",
    "front": "What's stage 1 of aspect-of-slope relocation, and the IMS target time for the full procedure on a known slope?",
    "back": "**Stage 1: take a compass bearing directly down the fall line** of the slope you're standing on (the aspect bearing). **Target time: under 2 minutes** for the full procedure.",
    "tags": [
      "L3",
      "D7.2",
      "combined-techniques"
    ]
  },
  {
    "id": "D10.1-13",
    "title": "Pole-and-cord conditions",
    "front": "The pole-and-cord technique is appropriate when **all three** of which conditions hold?",
    "back": "(1) **Visibility <5–10 m.** (2) **Terrain has hidden hazards** (drops, cornices, crevasse margins, sudden steepening). (3) **A bearing-walked approach is the only available navigation option.**",
    "tags": [
      "L3",
      "D8.2",
      "poor-visibility"
    ]
  },
  {
    "id": "D10.1-14",
    "title": "Eleven route card fields",
    "front": "Name the eleven standard fields of an IMS-style route card.",
    "back": "1. Leg number\n2. Start point and altitude\n3. End point and altitude\n4. Compass bearing (magnetic)\n5. Distance (map)\n6. Estimated time\n7. Altimeter trigger height\n8. Key terrain features\n9. Avalanche assessment\n10. Decision point criteria\n11. Escape route",
    "tags": [
      "L3",
      "D9.1",
      "route-cards"
    ]
  },
  {
    "id": "D10.1-15",
    "title": "Pre-agreed criteria standard",
    "front": "A pre-agreed go / no-go criterion needs which three components?",
    "back": "(1) **A specific trigger** (a measurable condition). (2) **A specific action** (turn around, alternative line, etc.). (3) **A named decision point** (where the criterion is checked).",
    "tags": [
      "L3",
      "D9.3",
      "decision-making"
    ]
  },
  {
    "id": "L1-01",
    "title": "Topographic map purpose",
    "front": "What is a topographic map *for*?",
    "back": "Helping you understand and navigate the **shape of the land** itself — not just getting from town to town. Designed for terrain interpretation and route choice in mountain navigation.",
    "tags": [
      "L1",
      "B1.1",
      "map-basics"
    ]
  },
  {
    "id": "L1-02",
    "title": "Three views of a landscape",
    "front": "Name three different ways of viewing the same landscape on paper / screen.",
    "back": "(1) **Road map** — roads and settlements; weak on terrain. (2) **Satellite image** — real surfaces; harder to interpret quickly. (3) **Topographic map** — terrain shape and features via symbols, colours, contours.",
    "tags": [
      "L1",
      "B1.1",
      "map-basics"
    ]
  },
  {
    "id": "L1-03",
    "title": "Bird's-eye view definition",
    "front": "What does \"bird's-eye view\" mean for map reading?",
    "back": "The map shows the landscape **from directly above**. Good map reading is about translating between this overhead view and the ground view you actually experience.",
    "tags": [
      "L1",
      "B1.2",
      "perspective"
    ]
  },
  {
    "id": "L1-04",
    "title": "Five-part map opening routine",
    "front": "What five things should you check first on any unfamiliar map?",
    "back": "**(1) Title. (2) Scale. (3) Legend. (4) North arrow. (5) Grid.** Develop this as a repeatable opening routine.",
    "tags": [
      "L1",
      "B2.1",
      "map-anatomy"
    ]
  },
  {
    "id": "L1-05",
    "title": "Why scale comes before measurement",
    "front": "Why check the scale before measuring anything?",
    "back": "Distances on the page are meaningless without knowing what the scale is — and a printed PDF may have been re-sized, so the original scale may no longer be accurate.",
    "tags": [
      "L1",
      "B2.1",
      "scale"
    ]
  },
  {
    "id": "L1-06",
    "title": "Why check the legend",
    "front": "Why always check the legend before trusting a symbol?",
    "back": "**Symbols and styles vary between national series.** A legend confirms what the cartographer actually used. Colour gives a quick impression; the legend confirms the meaning.",
    "tags": [
      "L1",
      "B2.1",
      "map-anatomy"
    ]
  },
  {
    "id": "L1-07",
    "title": "Five-colour system: blue",
    "front": "On a topographic map, what does **blue** usually represent?",
    "back": "**Water** — rivers, streams, lakes, glaciers (when drawn in blue/cyan).",
    "tags": [
      "L1",
      "B3.1",
      "colours"
    ]
  },
  {
    "id": "L1-08",
    "title": "Five-colour system: brown",
    "front": "What does **brown** usually represent?",
    "back": "**Contour lines and elevation features.** Index contours may be drawn slightly thicker.",
    "tags": [
      "L1",
      "B3.1",
      "colours"
    ]
  },
  {
    "id": "L1-09",
    "title": "Five-colour system: green",
    "front": "What does **green** usually represent?",
    "back": "**Vegetation** — woods, forest cover. Density of green often varies with vegetation density.",
    "tags": [
      "L1",
      "B3.1",
      "colours"
    ]
  },
  {
    "id": "L1-10",
    "title": "Five-colour system: black",
    "front": "What does **black** usually represent?",
    "back": "**Cultural / man-made features** — buildings, roads (when not coloured), tracks, fences, boundaries, text labels.",
    "tags": [
      "L1",
      "B3.1",
      "colours"
    ]
  },
  {
    "id": "L1-11",
    "title": "Five-colour system: white / grey",
    "front": "What does **white or grey** usually represent in alpine areas?",
    "back": "**Snow, ice, and rock.** White for permanent snow / glacier; grey or stippled for rock and scree.",
    "tags": [
      "L1",
      "B3.1",
      "colours"
    ]
  },
  {
    "id": "L1-12",
    "title": "1:25,000 scale rule",
    "front": "On a 1:25,000 map, 1 cm represents how many metres on the ground?",
    "back": "**250 m** (1 cm = 25,000 cm = 250 m).",
    "tags": [
      "L1",
      "B4.1",
      "scale"
    ]
  },
  {
    "id": "L1-13",
    "title": "1:50,000 scale rule",
    "front": "On a 1:50,000 map, 1 cm represents how many metres on the ground?",
    "back": "**500 m** (1 cm = 50,000 cm = 500 m).",
    "tags": [
      "L1",
      "B4.1",
      "scale"
    ]
  },
  {
    "id": "L1-14",
    "title": "Comparing scales",
    "front": "On the page, which covers more ground per cm — 1:25,000 or 1:50,000?",
    "back": "**1:50,000.** Each cm of paper covers twice the ground at 1:50,000 (500 m) compared to 1:25,000 (250 m).",
    "tags": [
      "L1",
      "B4.1",
      "scale"
    ]
  },
  {
    "id": "L1-15",
    "title": "When to use 1:25,000 vs 1:50,000",
    "front": "When would you choose 1:25,000 over 1:50,000?",
    "back": "**1:25,000** when terrain detail matters (steep, complex, mixed-feature ground). **1:50,000** for overview and longer-range route planning where fine detail isn't needed.",
    "tags": [
      "L1",
      "B4.1",
      "scale"
    ]
  },
  {
    "id": "L1-16",
    "title": "Print scaling caveat",
    "front": "Why must you check print scaling on a PDF extract before trusting measurements?",
    "back": "If the PDF has been printed at the wrong size (e.g. \"fit to page\"), the original scale no longer applies. Always verify the printed scale bar matches the stated scale before measuring.",
    "tags": [
      "L1",
      "B4.1",
      "scale"
    ]
  },
  {
    "id": "L1-17",
    "title": "Four-figure grid reference order",
    "front": "What's the correct order when reading a four-figure grid reference?",
    "back": "**Eastings first, then northings.** \"Along the corridor, then up the stairs.\"",
    "tags": [
      "L1",
      "B5.2",
      "grid"
    ]
  },
  {
    "id": "L1-18",
    "title": "What a four-figure grid identifies",
    "front": "Does a four-figure grid reference identify an exact point or a square?",
    "back": "**A grid square** — typically 1 km × 1 km on a 1:25,000 map. A six-figure reference identifies a 100 m square; an eight-figure reference identifies a point.",
    "tags": [
      "L1",
      "B5.2",
      "grid"
    ]
  },
  {
    "id": "L1-19",
    "title": "North at the top",
    "front": "If north is at the top of the map, which direction is to the right?",
    "back": "**East.** (Clockwise from north: N, E, S, W.)",
    "tags": [
      "L1",
      "B6.1",
      "orientation"
    ]
  },
  {
    "id": "L1-20",
    "title": "Why rotate the map",
    "front": "Why does rotating the map to match the terrain make navigation easier?",
    "back": "It eliminates the **mental rotation step** between what you see on the map and what you see on the ground. Features line up the way they actually appear from where you're standing.",
    "tags": [
      "L1",
      "B6.2",
      "orientation"
    ]
  },
  {
    "id": "L1-21",
    "title": "Map symbol families",
    "front": "What are the four broad families of map symbol that the legend organises?",
    "back": "Roughly: **(1) Cultural** (buildings, roads, tracks). **(2) Natural / vegetation** (forest, scrub, water). **(3) Relief** (contours, spot heights, cliffs). **(4) Boundaries / labels** (administrative borders, place names).",
    "tags": [
      "L1",
      "B3.2",
      "map-anatomy"
    ]
  },
  {
    "id": "L1-22",
    "title": "Building cluster on the map",
    "front": "A cluster of small black rectangles on the map most likely means what?",
    "back": "**Buildings** — typically a hamlet, village, hut group, or farm complex.",
    "tags": [
      "L1",
      "B1.2",
      "map-reading"
    ]
  },
  {
    "id": "L1-23",
    "title": "Blue line at the lowest point",
    "front": "A blue line at the lowest point of a small map area most likely means what?",
    "back": "A **watercourse** — stream or river. Water lies in low ground.",
    "tags": [
      "L1",
      "B1.2",
      "map-reading"
    ]
  },
  {
    "id": "L1-24",
    "title": "Close brown contour lines",
    "front": "Close brown contour lines mean what?",
    "back": "**Steep ground.** The closer the contours, the steeper the slope.",
    "tags": [
      "L1",
      "B1.2",
      "contour-fundamentals"
    ]
  },
  {
    "id": "L1-25",
    "title": "Reading colour first, legend second",
    "front": "What's the right order for an unfamiliar map: colour or legend first?",
    "back": "**Colour for quick impression, legend to confirm.** Colours give you the broad pattern in seconds; the legend confirms the precise meaning of the symbols when it matters.",
    "tags": [
      "L1",
      "B3.2",
      "map-anatomy"
    ]
  },
  {
    "id": "L1-26",
    "title": "Index contours",
    "front": "What's an index contour, and how do you spot it?",
    "back": "Every fifth (sometimes tenth) contour drawn **slightly thicker** to make height-counting easier. The elevation is often labelled on or near the index line.",
    "tags": [
      "L1",
      "B3.1",
      "contour-fundamentals"
    ]
  },
  {
    "id": "L1-27",
    "title": "Spot height",
    "front": "What's a spot height?",
    "back": "A **small marker on the map giving the elevation of a specific point** — usually a summit, col, or notable feature. The most reliable elevation reference inside a contour-free area.",
    "tags": [
      "L1",
      "B3.1",
      "relief"
    ]
  },
  {
    "id": "L1-28",
    "title": "Three reasons topo > road map for mountain",
    "front": "Give three reasons a topographic map is more useful than a road map in mountain terrain.",
    "back": "(1) Shows **terrain shape**. (2) Shows **slope steepness** via contour spacing. (3) Combines **natural and man-made features** at scale. (Bonus: lets you judge route practicality before committing.)",
    "tags": [
      "L1",
      "B1.1",
      "map-basics"
    ]
  },
  {
    "id": "L1-29",
    "title": "Standard map orientation",
    "front": "When a map is drawn \"north-up\", which side of the page is north?",
    "back": "**The top.** All major topographic series are drawn this way unless explicitly stated otherwise.",
    "tags": [
      "L1",
      "B6.1",
      "orientation"
    ]
  },
  {
    "id": "L1-30",
    "title": "Reading the corner",
    "front": "A bridge crossing a stream is shown on the map. Contours are close to the east, wider to the west. What does the ground look like?",
    "back": "The **stream is in a low point** at the bridge. The ground **rises steeply to the east** (close contours) and **rises gently to the west** (wide contours). Buildings, if present, will likely sit on the gentler western side.",
    "tags": [
      "L1",
      "B1.2",
      "map-reading"
    ]
  },
  {
    "id": "L2-01",
    "title": "Contour line definition",
    "front": "What is a contour line?",
    "back": "**A line on the map joining points of equal elevation** above sea level. Every point on a single contour line is at the same height.",
    "tags": [
      "L2",
      "C1.1",
      "contour-fundamentals"
    ]
  },
  {
    "id": "L2-02",
    "title": "Contour interval",
    "front": "What's a contour interval?",
    "back": "The **vertical distance between adjacent contour lines.** On a 1:25,000 alpine map this is typically 10 m; on 1:50,000 it's typically 20 m.",
    "tags": [
      "L2",
      "C1.1",
      "contour-fundamentals"
    ]
  },
  {
    "id": "L2-03",
    "title": "Contour spacing rule of thumb",
    "front": "State the C1.2 rule of thumb relating contour spacing to slope angle (1:25,000, 10 m contours).",
    "back": "Roughly: **3 mm spacing ≈ 30°**, **5–6 mm ≈ 12°**, **10 mm ≈ 6°**. Closer than 3 mm = steeper than 30°. The rule scales linearly with the contour interval and map scale.",
    "tags": [
      "L2",
      "C1.2",
      "steepness"
    ]
  },
  {
    "id": "L2-04",
    "title": "Contour spacing → slope intuition",
    "front": "What does **very tightly packed** contour spacing tell you?",
    "back": "**Very steep ground** — possibly cliff or near-cliff. If the contours appear merged, suspect a cliff band (look for rock symbology to confirm).",
    "tags": [
      "L2",
      "C1.2",
      "steepness"
    ]
  },
  {
    "id": "L2-05",
    "title": "Contour spacing wide",
    "front": "What does **widely spaced** contour spacing tell you?",
    "back": "**Gentle ground** — flat plateau, broad bench, or shallow rise. May feel almost level on the ground.",
    "tags": [
      "L2",
      "C1.2",
      "steepness"
    ]
  },
  {
    "id": "L2-06",
    "title": "Sharp peak summit pattern",
    "front": "What contour pattern identifies a sharp peak summit?",
    "back": "**Tightly spaced closed loops** with a single clear high point, often marked by a spot height. Steep on most or all sides.",
    "tags": [
      "L2",
      "C2.1",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-07",
    "title": "Rounded summit pattern",
    "front": "What contour pattern identifies a rounded summit?",
    "back": "**Widely spaced closed loops**, often with a broad central area. The high point can feel ambiguous on the ground. Common on grass-covered or weathered tops.",
    "tags": [
      "L2",
      "C2.1",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-08",
    "title": "Plateau-like high pattern",
    "front": "What contour pattern identifies a plateau-like high?",
    "back": "**A single closed loop around a broad nearly contour-free area**, with a small spot height marking the actual peak. Common on Austrian Alpine plateaux and broad shoulders.",
    "tags": [
      "L2",
      "C2.1",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-09",
    "title": "Valley pattern",
    "front": "What contour pattern identifies a valley?",
    "back": "**A V or U shape pointing uphill** (towards higher ground), with a watercourse running down the centre. The opposite of a spur.",
    "tags": [
      "L2",
      "C2.2",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-10",
    "title": "Spur pattern",
    "front": "What contour pattern identifies a spur?",
    "back": "**A V or U shape pointing downhill** (away from higher ground). Projects out from a parent feature like a peak or ridge.",
    "tags": [
      "L2",
      "C2.3",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-11",
    "title": "Inverse-pairing rule",
    "front": "State the inverse-pairing rule for contour V-shapes.",
    "back": "**V points uphill = valley; V points downhill = spur.** This is the foundational pattern for distinguishing the two most common alpine features.",
    "tags": [
      "L2",
      "C2.3",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-12",
    "title": "Ridge pattern",
    "front": "What distinguishes a ridge from a spur on the map?",
    "back": "A **ridge** is a **long, sustained linear high feature** — a continuous backbone connecting summits or cols. A **spur** is a shorter projection off a ridge or peak.",
    "tags": [
      "L2",
      "C2.3",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-13",
    "title": "Gully pattern",
    "front": "What contour pattern identifies a gully?",
    "back": "**A narrow V-shape pointing uphill, tightly compressed**, often with very close contours on both flanks. Different from a valley by being narrow and steep-sided.",
    "tags": [
      "L2",
      "C2.2",
      "feature-recognition"
    ]
  },
  {
    "id": "L2-14",
    "title": "Col pattern",
    "front": "What contour pattern identifies a col (saddle)?",
    "back": "**The lowest point on a ridge between two summits.** Two opposite sides of contours rise (towards the two summits); two opposite sides fall (towards the two valleys).",
    "tags": [
      "L2",
      "C3.3",
      "advanced-features"
    ]
  },
  {
    "id": "L2-15",
    "title": "Bowl headwall + flanks",
    "front": "Where on a bowl are contours tightest, and where wider?",
    "back": "**Tightest at the back (the headwall)**, **wider on the flanks**. Reflects the steep cliff-like back wall of the corrie shape and the gentler side slopes.",
    "tags": [
      "L2",
      "C3.1",
      "advanced-features"
    ]
  },
  {
    "id": "L2-16",
    "title": "Cliff band single cue is not enough",
    "front": "Why is \"merged contours\" alone not enough to identify a cliff band?",
    "back": "Merged contours can indicate any very steep slope, not necessarily rock. The **rock symbology** (hatching, stippling, or shading depending on the map series) confirms it. Either cue alone can mislead.",
    "tags": [
      "L2",
      "C3.4",
      "advanced-features"
    ]
  },
  {
    "id": "L2-17",
    "title": "Convex roll",
    "front": "What's a convex roll on a slope?",
    "back": "**A point where the slope rolls over and steepens below.** Hard to spot from above (you can't see what's below the roll). On the map, contours that suddenly tighten beneath wider contours are the cue.",
    "tags": [
      "L2",
      "C3.4",
      "hazards"
    ]
  },
  {
    "id": "L2-18",
    "title": "Concave slope",
    "front": "What's a concave slope, and how does it appear on the map?",
    "back": "**A slope that gets gentler as you descend** (steep at the top, gentler below). Contours tight at the top, wider towards the bottom.",
    "tags": [
      "L2",
      "C3.4",
      "slope-shape"
    ]
  },
  {
    "id": "L2-19",
    "title": "Aspect definition",
    "front": "What's \"aspect\"?",
    "back": "**The compass direction the slope faces** — i.e. the direction the slope falls towards. A north-facing slope falls towards the north.",
    "tags": [
      "L2",
      "C4.1",
      "aspect"
    ]
  },
  {
    "id": "L2-20",
    "title": "Eight aspect directions",
    "front": "Name the eight aspect directions in order, starting from north.",
    "back": "**N, NE, E, SE, S, SW, W, NW.** (45° increments around the compass.)",
    "tags": [
      "L2",
      "C4.2",
      "aspect"
    ]
  },
  {
    "id": "L2-21",
    "title": "Why eight not four",
    "front": "Why use eight aspect directions rather than four?",
    "back": "Avalanche bulletins, sun exposure and snow stability all vary substantially within 45° of aspect. A \"south-facing\" slope at SW behaves very differently from a true S aspect — eight directions captures this; four hides it.",
    "tags": [
      "L2",
      "C4.2",
      "aspect"
    ]
  },
  {
    "id": "L2-22",
    "title": "Reading aspect from contour orientation",
    "front": "How do you read aspect from contour orientation alone?",
    "back": "**The aspect is perpendicular to the contour, in the downhill direction.** Imagine a ball rolling down the slope at the point — the direction it rolls is the aspect.",
    "tags": [
      "L2",
      "C4.1",
      "aspect"
    ]
  },
  {
    "id": "L2-23",
    "title": "Cross-section concept",
    "front": "What's a cross-section, and what does it teach you?",
    "back": "**A side-view profile of a slope or ridge cut along a chosen line.** Helps translate the overhead contour pattern into the side-on shape you'd actually see standing there.",
    "tags": [
      "L2",
      "C5.1",
      "visualisation"
    ]
  },
  {
    "id": "L2-24",
    "title": "Photo matching",
    "front": "What's \"photo matching\" as a Level 2 visualisation skill?",
    "back": "**Looking at a photograph of terrain and identifying which contour patterns on the map produce that scene.** Strengthens the bidirectional translation between map and ground view.",
    "tags": [
      "L2",
      "C5.2",
      "visualisation"
    ]
  },
  {
    "id": "L2-25",
    "title": "\"If I stood here\" structure",
    "front": "What's the \"If I stood here...\" technique?",
    "back": "**A spoken or written exercise where you stand (mentally) at a marked point on the map and describe what the surroundings would look like in front, behind, left and right.** Uses the four-part structure for discipline.",
    "tags": [
      "L2",
      "C5.3",
      "visualisation"
    ]
  },
  {
    "id": "L2-26",
    "title": "Underfoot description",
    "front": "What goes in the \"underfoot\" part of the four-part standing description?",
    "back": "**What's beneath your feet** — snow type and surface, rock, vegetation, ice, scree. Specific where possible (e.g. \"firm spring snow with a thin breakable crust\").",
    "tags": [
      "L2",
      "C5.3",
      "visualisation"
    ]
  },
  {
    "id": "L2-27",
    "title": "Slope-and-aspect description",
    "front": "What goes in the \"slope and aspect\" part?",
    "back": "**The angle and aspect of the slope you're standing on.** Use C1.2 steepness vocabulary and eight-direction aspect terms.",
    "tags": [
      "L2",
      "C5.3",
      "visualisation"
    ]
  },
  {
    "id": "L2-28",
    "title": "Near vs far features",
    "front": "What's the distinction between \"near features\" and \"far features\" in the standing description?",
    "back": "**Near features** = within ~500 m (the immediate slope, nearby spurs, the next valley edge). **Far features** = beyond, named summits, distant ridges, large valleys.",
    "tags": [
      "L2",
      "C5.3",
      "visualisation"
    ]
  },
  {
    "id": "L2-29",
    "title": "Three line types",
    "front": "Name the three classic line types for traversing a slope on skis.",
    "back": "**(1) Direct** (straight up or down). **(2) Contour-following** (across the slope at constant height). **(3) Zig-zag with kick turns** (alternating diagonals).",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "L2-30",
    "title": "When to choose direct",
    "front": "When is a direct line the right choice?",
    "back": "**On gentle ground (under ~10°)** where the angle is comfortable, **or on a short steep section** where zig-zagging would lose more time than it saves.",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "L2-31",
    "title": "When to choose contour-following",
    "front": "When is a contour-following line the right choice?",
    "back": "**When you need to maintain altitude across a slope** to reach a feature on the other side, or when the gradient is too steep to skin direct but doesn't require kick turns.",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "L2-32",
    "title": "When to choose zig-zag",
    "front": "When is a zig-zag with kick turns the right choice?",
    "back": "**On sustained steeper ground** (12–15°+) where direct skinning would slip and contour-following would gain too little altitude. Each kick turn adds time but gives gradient control.",
    "tags": [
      "L2",
      "C6.1",
      "route-choice"
    ]
  },
  {
    "id": "L2-33",
    "title": "Terrain-trap example: gully",
    "front": "Why is a gully a terrain trap?",
    "back": "**It concentrates moving snow.** A small slide that would be harmless on an open slope can fill a gully and bury you deeply. Configuration creates the disproportionate consequence.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "L2-34",
    "title": "Terrain-trap example: single-mouth bowl",
    "front": "Why is a single-mouth bowl a terrain trap?",
    "back": "**It removes the exit.** Snow funnelled into the bowl mouth has nowhere to escape; a slide deposits a deep concentrated pile in the only way out.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "L2-35",
    "title": "Terrain-trap example: slope above cliff",
    "front": "Why is a slope above a cliff band a terrain trap?",
    "back": "**It adds a vertical drop to any slide or fall.** A 30° slope is not a terrain trap on its own; a 30° slope above a cliff is.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "L2-36",
    "title": "Terrain trap is about consequence",
    "front": "Is \"terrain trap\" about slope angle or consequence?",
    "back": "**Consequence.** A piece of ground earns the label not because it's steep, but because the configuration makes a small event have a disproportionate outcome.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "L2-37",
    "title": "C7.2 four families of feature",
    "front": "The C7.2 standard A→B→C→D walk is configured to span which four feature families?",
    "back": "**A: col / saddle. B: bowl. C: spur. D: valley floor with stream.** Each tests a different aspect of the description structure.",
    "tags": [
      "L2",
      "C7.2",
      "integration"
    ]
  },
  {
    "id": "L2-38",
    "title": "Bulletin-aware route choice",
    "front": "\"Heightened danger on N through E aspects above 2,200 m\" — what does this rule out?",
    "back": "**Skiing or skinning on slopes facing N, NE, E or anything in that arc, at altitudes above 2,200 m**, until you've decided the heightened-danger ground is acceptable risk for that day.",
    "tags": [
      "L2",
      "C6.2",
      "hazards"
    ]
  },
  {
    "id": "L2-39",
    "title": "Level 3 readiness target",
    "front": "What's the broad readiness standard for moving from Level 2 to Level 3?",
    "back": "**C7.1 quiz at 12+ correct out of 15** with no family-level errors on feature identification, plus a strong C7.2 narration with the four-part structure intact at all four stops.",
    "tags": [
      "L2",
      "C7.1",
      "integration"
    ]
  },
  {
    "id": "L2-40",
    "title": "Family vs sub-type errors",
    "front": "Why are \"family-level\" errors on feature identification more serious than \"sub-type\" errors?",
    "back": "A family error (calling a spur a valley) means the **inverse-pairing rule hasn't stuck** — the foundational pattern is wrong. A sub-type error (spur vs ridge) is a refinement that takes more practice to internalise. Family errors trigger recycling; sub-type errors get coached.",
    "tags": [
      "L2",
      "C7.1",
      "integration"
    ]
  },
  {
    "id": "L3-01",
    "title": "Compass: direction-of-travel arrow",
    "front": "What does the direction-of-travel arrow do?",
    "back": "**Fixed on the baseplate.** Points in the direction you're going. You align the rest of the compass to it; you walk along the line it indicates.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-02",
    "title": "Compass: orienting arrow",
    "front": "What does the orienting arrow do?",
    "back": "**On the floor of the rotating bezel.** It's the alignment target for the magnetic needle when you've turned the bezel to set the bearing.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-03",
    "title": "Compass: rotating bezel",
    "front": "What does the rotating bezel do?",
    "back": "**The compass dial that turns.** It carries the orienting arrow and orienting lines; rotating it lets you set or read a bearing in degrees.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-04",
    "title": "Compass: baseplate",
    "front": "What does the baseplate do?",
    "back": "**The clear plastic body of the compass.** Holds the bezel, carries the direction-of-travel arrow, has measurement scales for use against the map.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-05",
    "title": "Compass: orienting lines",
    "front": "What are the orienting lines, and what do you align them with?",
    "back": "**The parallel lines on the floor of the bezel.** You align them with the **grid lines on the map** when taking a bearing.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-06",
    "title": "Compass: magnetic needle",
    "front": "What's special about the magnetic needle?",
    "back": "**It always points to magnetic north** when free to swing, regardless of how you hold the compass. The red tip is the north end.",
    "tags": [
      "L3",
      "D1.1",
      "compass"
    ]
  },
  {
    "id": "L3-07",
    "title": "\"Red Fred in the shed\"",
    "front": "What does \"red Fred in the shed\" mean for compass use?",
    "back": "**The mnemonic for setting a bearing.** Once the bearing is set on the bezel, rotate yourself (and the compass) until the **red end of the magnetic needle (\"Red Fred\") sits inside the orienting arrow (\"the shed\")**. Then walk in the direction the DTA points.",
    "tags": [
      "L3",
      "D2.3",
      "compass"
    ]
  },
  {
    "id": "L3-08",
    "title": "Bearing accuracy IMS standard",
    "front": "What's the IMS / EMS bearing-accuracy standard?",
    "back": "**Within 2°.** Tighter accuracy is unnecessary at the resolution of mountain navigation; looser is unsafe over long legs.",
    "tags": [
      "L3",
      "D1.2",
      "accuracy"
    ]
  },
  {
    "id": "L3-09",
    "title": "Bearing time IMS standard",
    "front": "What's the IMS / EMS bearing-reading time standard?",
    "back": "**Under 60 seconds**, from looking at the map to having a settled bearing on the bezel ready to walk on.",
    "tags": [
      "L3",
      "D1.2",
      "accuracy"
    ]
  },
  {
    "id": "L3-10",
    "title": "Magnetic vs grid bearing",
    "front": "What's the difference between a grid bearing and a magnetic bearing?",
    "back": "**Grid bearing** = read off the map relative to grid north. **Magnetic bearing** = the compass reading you need to actually walk on, accounting for local magnetic variation.",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-11",
    "title": "East variation rule",
    "front": "How do you adjust a grid bearing for **east** variation?",
    "back": "**Add the variation to the grid bearing.** \"East is least... wait — for grid → magnetic, east means add.\" Grid 178° + 2° east = magnetic 180°.",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-12",
    "title": "West variation rule",
    "front": "How do you adjust a grid bearing for **west** variation?",
    "back": "**Subtract the variation from the grid bearing.** Grid 178° - 2° west = magnetic 176°.",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-13",
    "title": "Reverse: magnetic to grid",
    "front": "Going the other way: how do you adjust a magnetic bearing to a grid bearing for east variation?",
    "back": "**Subtract** the variation. (The adjustment reverses when you reverse the direction of conversion.)",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-14",
    "title": "Why magnetic variation matters at all",
    "front": "Why does magnetic variation matter?",
    "back": "**Magnetic north and grid north are not the same point.** The compass points to magnetic north; the map is drawn relative to grid north. A few degrees of difference, applied over hundreds of metres, becomes a position error of tens of metres.",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-15",
    "title": "Variation changes over time",
    "front": "Does magnetic variation change over time?",
    "back": "**Yes — slowly.** Each map sheet states the variation at publication date and the annual rate of change. For modern maps the change is typically a fraction of a degree per year; over a decade it adds up.",
    "tags": [
      "L3",
      "D2.2",
      "bearings"
    ]
  },
  {
    "id": "L3-16",
    "title": "Bearing reading: edge alignment",
    "front": "Step 1 of bearing-from-map: where does the baseplate edge go?",
    "back": "**Along the line from start to destination, with the direction-of-travel arrow pointing towards the destination.** Get this wrong and the bearing is reversed.",
    "tags": [
      "L3",
      "D2.1",
      "bearings"
    ]
  },
  {
    "id": "L3-17",
    "title": "Bearing reading: bezel rotation",
    "front": "Step 2 of bearing-from-map: what do you rotate the bezel until you see?",
    "back": "**Until the parallel orienting lines on the bezel floor align with the grid lines on the map** (and \"north\" on the bezel points toward grid north on the map).",
    "tags": [
      "L3",
      "D2.1",
      "bearings"
    ]
  },
  {
    "id": "L3-18",
    "title": "Bearing reading: take off the map",
    "front": "Step 3 of bearing-from-map: why take the compass off the map before reading?",
    "back": "**So the magnetic needle is no longer constrained or distracted** by metal in your environment, and so the reading reflects what you'll actually see in the field.",
    "tags": [
      "L3",
      "D2.1",
      "bearings"
    ]
  },
  {
    "id": "L3-19",
    "title": "Bearing reading: read the bearing",
    "front": "Step 4: where do you read the bearing from?",
    "back": "**Where the direction-of-travel arrow meets the bezel scale** (often labelled \"READ HERE\" or under an index mark on the baseplate).",
    "tags": [
      "L3",
      "D2.1",
      "bearings"
    ]
  },
  {
    "id": "L3-20",
    "title": "Walking on a bearing: drift",
    "front": "What's \"drift\" when walking on a bearing?",
    "back": "**The lateral deviation between your intended line and your actual line** as you walk. Caused by terrain steering you, incorrect compass holding, or distraction.",
    "tags": [
      "L3",
      "D3.1",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-21",
    "title": "Drift target: 15 m / 100 m",
    "front": "What's the drift target for walking on a bearing in metres per metres of travel?",
    "back": "**Less than 15 m drift per 100 m of travel.** Equivalent to ~9° angular error sustained.",
    "tags": [
      "L3",
      "D3.1",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-22",
    "title": "Aiming off",
    "front": "What's \"aiming off\" and when do you do it?",
    "back": "**Deliberately bearing-off your target by a few degrees so you arrive at a known point on a known side of the target**, rather than risking arriving uncertain whether to turn left or right. Useful when the target is on a linear feature like a ridge or stream.",
    "tags": [
      "L3",
      "D3.2",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-23",
    "title": "Back bearing definition",
    "front": "What's a back bearing?",
    "back": "**The reverse of a forward bearing — the bearing FROM the destination back to your starting point.** Used to verify position by sighting back at where you came from.",
    "tags": [
      "L3",
      "D3.2",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-24",
    "title": "Back bearing arithmetic",
    "front": "State the back-bearing arithmetic rule.",
    "back": "**If forward bearing ≥ 180°, subtract 180°. If forward bearing < 180°, add 180°.** Both branches keep the result within 0–360°. (Adding 180° and wrapping at 360° gives the same answer mathematically.)",
    "tags": [
      "L3",
      "D3.2",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-25",
    "title": "Resection definition",
    "front": "What's resection?",
    "back": "**A way of fixing your position on the map by taking bearings to two or more visible features**, then drawing reverse-bearing lines from each on the map. Where the lines intersect is your position.",
    "tags": [
      "L3",
      "D3.3",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-26",
    "title": "Resection: two features minimum",
    "front": "Why is two the minimum number of features for a resection?",
    "back": "**Two lines define a single intersection point.** One line gives a line of position only — you could be anywhere along it. (Three features give a triangle of error and are more reliable.)",
    "tags": [
      "L3",
      "D3.3",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-27",
    "title": "Resection: 90° optimum",
    "front": "Why is ~90° the optimum angular separation for resection features?",
    "back": "**At 90° the two bearing lines cross sharply, so a small bearing error produces a small position error.** Closer-together or near-opposite features cross at shallow angles, multiplying any bearing error.",
    "tags": [
      "L3",
      "D3.3",
      "ground-bearings"
    ]
  },
  {
    "id": "L3-28",
    "title": "Bearing-shapes drill",
    "front": "What's the \"bearing-shapes drill\"?",
    "back": "**Walk a known shape (typically a 100-pace square) on bearings only** — turn 90° at each corner, walk the next leg, etc. The closure error at the end is your accuracy benchmark.",
    "tags": [
      "L3",
      "D4.1",
      "accuracy"
    ]
  },
  {
    "id": "L3-29",
    "title": "Closure-error standard",
    "front": "What's the IMS / EMS closure-error standard for the 100-pace square drill?",
    "back": "**Less than 5 paces.** (Practitioners often hit 1–2 paces.)",
    "tags": [
      "L3",
      "D4.1",
      "accuracy"
    ]
  },
  {
    "id": "L3-30",
    "title": "Magnetic interference: principle",
    "front": "What's the principle behind the magnetic-interference distances?",
    "back": "**Steel deflects the needle at short range; electronics interfere at slightly shorter range.** Hence 50 cm for steel (bindings, ice axes), 30 cm for electronics (phones, radios).",
    "tags": [
      "L3",
      "D4.3",
      "accuracy"
    ]
  },
  {
    "id": "L3-31",
    "title": "Common interference mistake",
    "front": "What's the most common interference mistake when reading a bearing in the field?",
    "back": "**Holding the compass too close to your own body** — your phone in your jacket pocket, an ice axe across your back, a steel zip pull. Step away from your kit before reading.",
    "tags": [
      "L3",
      "D4.3",
      "accuracy"
    ]
  },
  {
    "id": "L3-32",
    "title": "Altimeter principle",
    "front": "How does an altimeter work?",
    "back": "**It measures atmospheric pressure and converts it to altitude** using a standard atmospheric model. As you go up, pressure drops; the altimeter converts the drop to a height reading.",
    "tags": [
      "L3",
      "D5.1",
      "altimeter"
    ]
  },
  {
    "id": "L3-33",
    "title": "Altimeter calibration",
    "front": "Why must you calibrate the altimeter at a known point?",
    "back": "**Atmospheric pressure changes with weather, not just altitude.** Calibrating at a known elevation point (a hut, summit, marked col) zeroes the altimeter against current pressure. Without calibration, weather drift accumulates as height error.",
    "tags": [
      "L3",
      "D5.2",
      "altimeter"
    ]
  },
  {
    "id": "L3-34",
    "title": "Altimeter drift",
    "front": "What does altimeter \"drift\" mean?",
    "back": "**The apparent change in your altitude reading even when you haven't moved** — caused by changes in atmospheric pressure (i.e. weather). Used by experienced navigators as a barometric trend indicator.",
    "tags": [
      "L3",
      "D5.3",
      "altimeter"
    ]
  },
  {
    "id": "L3-35",
    "title": "1 hPa = 8 m rule",
    "front": "State the 1 hPa altimeter rule.",
    "back": "**1 hPa of pressure change ≈ 8 m of apparent altitude change** in the lower troposphere. So if your altimeter says you've gained 16 m while standing still, atmospheric pressure has dropped 2 hPa.",
    "tags": [
      "L3",
      "D5.1",
      "altimeter"
    ]
  },
  {
    "id": "L3-36",
    "title": "Pressure trend interpretation",
    "front": "Why does barometric trend matter on a tour?",
    "back": "**Falling pressure means worsening weather** (cloud, precipitation, wind). The faster the fall, the more urgent the action. Rising pressure means stabilising or improving weather.",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "L3-37",
    "title": "Steady trend",
    "front": "What does a \"steady\" barometric trend mean numerically?",
    "back": "**Less than 0.1 hPa/hr sustained for 3 hours.** Weather is stable.",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "L3-38",
    "title": "Slow fall trend",
    "front": "What's the rate threshold for a \"slow fall\"?",
    "back": "**Less than 0.5 hPa/hr (falling).** Mild deterioration; watch for change of state.",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "L3-39",
    "title": "Moderate fall trend",
    "front": "What's the rate threshold for a \"moderate fall\"?",
    "back": "**0.5 to 1.0 hPa/hr (falling).** Active weather change in progress; consider whether to continue.",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "L3-40",
    "title": "Rapid fall trend",
    "front": "What's the rate threshold for a \"rapid fall\"?",
    "back": "**More than 1.0 hPa/hr (falling).** Significant deterioration imminent — strong reason to turn around or seek shelter.",
    "tags": [
      "L3",
      "D6.1",
      "barometer"
    ]
  },
  {
    "id": "L3-41",
    "title": "Aspect-of-slope relocation use case",
    "front": "When do you use aspect-of-slope relocation?",
    "back": "**When you've lost your exact position** (often in poor visibility) but you can stand on a slope and measure its aspect. The aspect narrows down which slope on the map you must be on.",
    "tags": [
      "L3",
      "D7.1",
      "combined-techniques"
    ]
  },
  {
    "id": "L3-42",
    "title": "Aspect-of-slope: stage 1",
    "front": "What's stage 1 of aspect-of-slope relocation?",
    "back": "**Take a compass bearing directly down the fall line of the slope you're standing on** — this is the aspect bearing.",
    "tags": [
      "L3",
      "D7.2",
      "combined-techniques"
    ]
  },
  {
    "id": "L3-43",
    "title": "Aspect-of-slope: matching to map",
    "front": "Once you have the aspect bearing, what do you do with the map?",
    "back": "**Identify all slopes on the map in the area you might be in that match this aspect.** Then narrow further using altitude (from the altimeter), nearby features, and the slope's apparent steepness.",
    "tags": [
      "L3",
      "D7.2",
      "combined-techniques"
    ]
  },
  {
    "id": "L3-44",
    "title": "Aspect-of-slope: target time",
    "front": "What's the IMS / EMS target time for aspect-of-slope relocation on a known slope?",
    "back": "**Under 2 minutes** for the full 4-stage procedure.",
    "tags": [
      "L3",
      "D7.2",
      "combined-techniques"
    ]
  },
  {
    "id": "L3-45",
    "title": "Visibility threshold for pole-and-cord",
    "front": "What's the visibility threshold below which pole-and-cord becomes appropriate?",
    "back": "**Less than 5–10 metres** of useful visibility. White-out conditions where you cannot see far enough to navigate by terrain features.",
    "tags": [
      "L3",
      "D8.2",
      "poor-visibility"
    ]
  },
  {
    "id": "L3-46",
    "title": "Why pole-and-cord works",
    "front": "What does the pole-and-cord technique actually do?",
    "back": "**A team member walks ahead on a fixed bearing on a known length of cord; the leader watches them disappear into the murk and reads where they end up.** This probes the ground for hazards and confirms the bearing line is safe before the team commits.",
    "tags": [
      "L3",
      "D8.2",
      "poor-visibility"
    ]
  },
  {
    "id": "L3-47",
    "title": "Pole-and-cord: not a routine technique",
    "front": "Why is pole-and-cord NOT a routine navigation technique?",
    "back": "**It's slow and uses up a team member as a probe.** Reserved for specific conditions: very poor visibility, hidden hazards, no other option. In normal visibility you use bearings + terrain + map.",
    "tags": [
      "L3",
      "D8.2",
      "poor-visibility"
    ]
  },
  {
    "id": "L3-48",
    "title": "Route card purpose",
    "front": "What's the route card for?",
    "back": "**A pre-tour planning artefact** that locks down the leg-by-leg navigation, timing, decision points, hazards, and escape routes — so under stress in the field you can refer back to a calm, considered plan rather than improvise.",
    "tags": [
      "L3",
      "D9.1",
      "route-cards"
    ]
  },
  {
    "id": "L3-49",
    "title": "Decision point criteria three components",
    "front": "A decision-point criterion needs which three components?",
    "back": "**(1) A specific trigger** (a measurable condition — e.g. \"bulletin upgraded to 4\"). **(2) A specific action** (turn around, take alternative line). **(3) A named decision point** (where on the route the criterion is checked).",
    "tags": [
      "L3",
      "D9.3",
      "decision-making"
    ]
  },
  {
    "id": "L3-50",
    "title": "Escape route on the route card",
    "front": "What's an escape route, and why is it on the route card?",
    "back": "**A pre-planned safe withdrawal line for any given leg.** Belongs on the route card so that if the decision-point criterion triggers a turn-around, you don't have to invent the retreat route under pressure — you've already planned it.",
    "tags": [
      "L3",
      "D9.4",
      "decision-making"
    ]
  },
  {
    "id": "X-01",
    "title": "IMS Nav Programme",
    "front": "What's the IMS Nav Programme?",
    "back": "**The International Mountain Safety / EMS-aligned navigation curriculum standard** that this workbook is built against. Defines the working accuracy, time and procedural standards used throughout Levels 1–3.",
    "tags": [
      "cross",
      "standards"
    ]
  },
  {
    "id": "X-02",
    "title": "BASI Alpine Level 4 ISTD",
    "front": "Where does this workbook sit in the BASI pathway?",
    "back": "**Preparation for the BASI Alpine Level 4 ISTD assessment**, specifically the IMS / EMS module. Levels 1–3 build the foundations; Level 4 is the assessed practical standard.",
    "tags": [
      "cross",
      "qualification"
    ]
  },
  {
    "id": "X-03",
    "title": "Underfoot vocabulary",
    "front": "Give five \"underfoot\" words you'd use in a standing description.",
    "back": "**Wind-affected snow, breakable crust, supportable crust, firm spring snow, soft fresh.** Plus surface words: scoured, sastrugi, glazed, cornice-edge, ice patches.",
    "tags": [
      "cross",
      "visualisation"
    ]
  },
  {
    "id": "X-04",
    "title": "Snow-stability heuristic for aspect",
    "front": "Why does aspect matter for avalanche risk?",
    "back": "**Snow on different aspects evolves differently** — sun exposure (solar slopes vs shaded), wind loading (lee vs windward), prevailing storm direction. Bulletins specify hazardous aspects accordingly.",
    "tags": [
      "cross",
      "hazards"
    ]
  },
  {
    "id": "X-05",
    "title": "Rule-of-thumb thinking",
    "front": "Why does the workbook lean on rules of thumb (3 mm = 30°, 1 hPa = 8 m, etc.) rather than precise calculation?",
    "back": "**Speed and stress.** In the field, with cold hands and limited time, an approximate answer in 5 seconds beats a precise answer in 30. Rules of thumb sit comfortably inside the IMS accuracy standard.",
    "tags": [
      "cross",
      "standards"
    ]
  },
  {
    "id": "X-06",
    "title": "Reading the map outside-in",
    "front": "What's \"outside-in\" map reading?",
    "back": "**Start with the broad context (large valleys, major summits, overall layout), then zoom in on the small detail.** The opposite of \"feature-hunting\" — you orient to the big shapes first, then place small features within them.",
    "tags": [
      "cross",
      "technique"
    ]
  },
  {
    "id": "X-07",
    "title": "Sustained vs spike measurements",
    "front": "Why does the barometric \"steady\" definition include \"sustained for 3 hours\"?",
    "back": "**A single low-or-high reading can be noise** (a passing gust, a sensor blip). A trend has to hold for a meaningful window before it counts. Rules of thumb that ignore time produce false alarms.",
    "tags": [
      "cross",
      "standards"
    ]
  },
  {
    "id": "X-08",
    "title": "Honesty in self-assessment",
    "front": "Why does the workbook emphasise honest self-assessment in C7.1, C7.2, D10.1 and D10.2?",
    "back": "**Self-deception in low-stakes practice causes failures in real assessment.** A learner who scores 5/5 confidence after several wrong answers hasn't engaged with the material; coaching the discrepancy is more useful than coaching the answers.",
    "tags": [
      "cross",
      "standards"
    ]
  },
  {
    "id": "X-09",
    "title": "Recycling vs progressing",
    "front": "When does a candidate \"recycle\" content vs \"progress\"?",
    "back": "**Recycle** (revisit specific Level X pages before continuing) when the error log shows family-level errors or sustained slow performance. **Progress** (move to the next level) when errors are sub-type only and time pressure is comfortable.",
    "tags": [
      "cross",
      "standards"
    ]
  },
  {
    "id": "X-10",
    "title": "The error log is the artefact",
    "front": "What does the workbook treat as the most useful artefact of the C7.1 / D10.1 quizzes?",
    "back": "**The error log.** The score is a snapshot; the error log is the action plan — every wrong or slow answer linked to a specific page to revisit and a specific action to take before the next session.",
    "tags": [
      "cross",
      "standards"
    ]
  }
];

export const DECKS: Deck[] = [
  {
    "id": "all",
    "title": "Everything",
    "description": "All 160 cards across all levels.",
    "primary": false,
    "cardIds": [
      "C7.1-01",
      "C7.1-02",
      "C7.1-03",
      "C7.1-04",
      "C7.1-05",
      "C7.1-06",
      "C7.1-07",
      "C7.1-08",
      "C7.1-09",
      "C7.1-10",
      "C7.1-11",
      "C7.1-12",
      "C7.1-13",
      "C7.1-14",
      "C7.1-15",
      "D10.1-01",
      "D10.1-02",
      "D10.1-03",
      "D10.1-04",
      "D10.1-05",
      "D10.1-06",
      "D10.1-07",
      "D10.1-08",
      "D10.1-09",
      "D10.1-10",
      "D10.1-11",
      "D10.1-12",
      "D10.1-13",
      "D10.1-14",
      "D10.1-15",
      "L1-01",
      "L1-02",
      "L1-03",
      "L1-04",
      "L1-05",
      "L1-06",
      "L1-07",
      "L1-08",
      "L1-09",
      "L1-10",
      "L1-11",
      "L1-12",
      "L1-13",
      "L1-14",
      "L1-15",
      "L1-16",
      "L1-17",
      "L1-18",
      "L1-19",
      "L1-20",
      "L1-21",
      "L1-22",
      "L1-23",
      "L1-24",
      "L1-25",
      "L1-26",
      "L1-27",
      "L1-28",
      "L1-29",
      "L1-30",
      "L2-01",
      "L2-02",
      "L2-03",
      "L2-04",
      "L2-05",
      "L2-06",
      "L2-07",
      "L2-08",
      "L2-09",
      "L2-10",
      "L2-11",
      "L2-12",
      "L2-13",
      "L2-14",
      "L2-15",
      "L2-16",
      "L2-17",
      "L2-18",
      "L2-19",
      "L2-20",
      "L2-21",
      "L2-22",
      "L2-23",
      "L2-24",
      "L2-25",
      "L2-26",
      "L2-27",
      "L2-28",
      "L2-29",
      "L2-30",
      "L2-31",
      "L2-32",
      "L2-33",
      "L2-34",
      "L2-35",
      "L2-36",
      "L2-37",
      "L2-38",
      "L2-39",
      "L2-40",
      "L3-01",
      "L3-02",
      "L3-03",
      "L3-04",
      "L3-05",
      "L3-06",
      "L3-07",
      "L3-08",
      "L3-09",
      "L3-10",
      "L3-11",
      "L3-12",
      "L3-13",
      "L3-14",
      "L3-15",
      "L3-16",
      "L3-17",
      "L3-18",
      "L3-19",
      "L3-20",
      "L3-21",
      "L3-22",
      "L3-23",
      "L3-24",
      "L3-25",
      "L3-26",
      "L3-27",
      "L3-28",
      "L3-29",
      "L3-30",
      "L3-31",
      "L3-32",
      "L3-33",
      "L3-34",
      "L3-35",
      "L3-36",
      "L3-37",
      "L3-38",
      "L3-39",
      "L3-40",
      "L3-41",
      "L3-42",
      "L3-43",
      "L3-44",
      "L3-45",
      "L3-46",
      "L3-47",
      "L3-48",
      "L3-49",
      "L3-50",
      "X-01",
      "X-02",
      "X-03",
      "X-04",
      "X-05",
      "X-06",
      "X-07",
      "X-08",
      "X-09",
      "X-10"
    ]
  },
  {
    "id": "review",
    "title": "Daily review",
    "description": "Cards that are due today, across every deck. Build it up by studying the focused decks first.",
    "primary": true,
    "pseudo": true,
    "cardIds": []
  },
  {
    "id": "l1",
    "title": "Level 1 — Map literacy foundations",
    "description": "Map basics, anatomy, colours, scale, grid, orientation.",
    "primary": true,
    "cardIds": [
      "L1-01",
      "L1-02",
      "L1-03",
      "L1-04",
      "L1-05",
      "L1-06",
      "L1-07",
      "L1-08",
      "L1-09",
      "L1-10",
      "L1-11",
      "L1-12",
      "L1-13",
      "L1-14",
      "L1-15",
      "L1-16",
      "L1-17",
      "L1-18",
      "L1-19",
      "L1-20",
      "L1-21",
      "L1-22",
      "L1-23",
      "L1-24",
      "L1-25",
      "L1-26",
      "L1-27",
      "L1-28",
      "L1-29",
      "L1-30"
    ]
  },
  {
    "id": "l2",
    "title": "Level 2 — Terrain interpretation",
    "description": "Contour fundamentals, feature recognition, advanced features, aspect, route choice.",
    "primary": true,
    "cardIds": [
      "C7.1-01",
      "C7.1-02",
      "C7.1-03",
      "C7.1-04",
      "C7.1-05",
      "C7.1-06",
      "C7.1-07",
      "C7.1-08",
      "C7.1-09",
      "C7.1-10",
      "C7.1-11",
      "C7.1-12",
      "C7.1-13",
      "C7.1-14",
      "C7.1-15",
      "L2-01",
      "L2-02",
      "L2-03",
      "L2-04",
      "L2-05",
      "L2-06",
      "L2-07",
      "L2-08",
      "L2-09",
      "L2-10",
      "L2-11",
      "L2-12",
      "L2-13",
      "L2-14",
      "L2-15",
      "L2-16",
      "L2-17",
      "L2-18",
      "L2-19",
      "L2-20",
      "L2-21",
      "L2-22",
      "L2-23",
      "L2-24",
      "L2-25",
      "L2-26",
      "L2-27",
      "L2-28",
      "L2-29",
      "L2-30",
      "L2-31",
      "L2-32",
      "L2-33",
      "L2-34",
      "L2-35",
      "L2-36",
      "L2-37",
      "L2-38",
      "L2-39",
      "L2-40"
    ]
  },
  {
    "id": "l3",
    "title": "Level 3 — Mountain navigation toolkit",
    "description": "Compass, bearings, accuracy, altimeter, barometer, combined techniques, route cards.",
    "primary": true,
    "cardIds": [
      "D10.1-01",
      "D10.1-02",
      "D10.1-03",
      "D10.1-04",
      "D10.1-05",
      "D10.1-06",
      "D10.1-07",
      "D10.1-08",
      "D10.1-09",
      "D10.1-10",
      "D10.1-11",
      "D10.1-12",
      "D10.1-13",
      "D10.1-14",
      "D10.1-15",
      "L3-01",
      "L3-02",
      "L3-03",
      "L3-04",
      "L3-05",
      "L3-06",
      "L3-07",
      "L3-08",
      "L3-09",
      "L3-10",
      "L3-11",
      "L3-12",
      "L3-13",
      "L3-14",
      "L3-15",
      "L3-16",
      "L3-17",
      "L3-18",
      "L3-19",
      "L3-20",
      "L3-21",
      "L3-22",
      "L3-23",
      "L3-24",
      "L3-25",
      "L3-26",
      "L3-27",
      "L3-28",
      "L3-29",
      "L3-30",
      "L3-31",
      "L3-32",
      "L3-33",
      "L3-34",
      "L3-35",
      "L3-36",
      "L3-37",
      "L3-38",
      "L3-39",
      "L3-40",
      "L3-41",
      "L3-42",
      "L3-43",
      "L3-44",
      "L3-45",
      "L3-46",
      "L3-47",
      "L3-48",
      "L3-49",
      "L3-50"
    ]
  },
  {
    "id": "c7-quiz",
    "title": "C7.1 quiz prep",
    "description": "Just the 15 mixed-contour quiz cards.",
    "primary": false,
    "cardIds": [
      "C7.1-01",
      "C7.1-02",
      "C7.1-03",
      "C7.1-04",
      "C7.1-05",
      "C7.1-06",
      "C7.1-07",
      "C7.1-08",
      "C7.1-09",
      "C7.1-10",
      "C7.1-11",
      "C7.1-12",
      "C7.1-13",
      "C7.1-14",
      "C7.1-15"
    ]
  },
  {
    "id": "d10-quiz",
    "title": "D10.1 quiz prep",
    "description": "Just the 15 Level 3 mixed-quiz cards.",
    "primary": false,
    "cardIds": [
      "D10.1-01",
      "D10.1-02",
      "D10.1-03",
      "D10.1-04",
      "D10.1-05",
      "D10.1-06",
      "D10.1-07",
      "D10.1-08",
      "D10.1-09",
      "D10.1-10",
      "D10.1-11",
      "D10.1-12",
      "D10.1-13",
      "D10.1-14",
      "D10.1-15"
    ]
  },
  {
    "id": "cross",
    "title": "Cross-cutting standards & vocabulary",
    "description": "IMS terminology, recycling vs progressing, error-log philosophy.",
    "primary": false,
    "cardIds": [
      "X-01",
      "X-02",
      "X-03",
      "X-04",
      "X-05",
      "X-06",
      "X-07",
      "X-08",
      "X-09",
      "X-10"
    ]
  }
];

export function getCard(id: string): Flashcard | undefined {
  return FLASHCARDS.find((c) => c.id === id);
}

export function getDeck(id: string): Deck | undefined {
  return DECKS.find((d) => d.id === id);
}

export function getCardsForDeck(id: string): Flashcard[] {
  const deck = getDeck(id);
  if (!deck) return [];
  return deck.cardIds.map((cid) => getCard(cid)).filter((c): c is Flashcard => Boolean(c));
}
